In [63]:
import pandas as pd

In [64]:
import numpy as np

In [65]:
import calendar

In [66]:
df = pd.read_csv("disasters.csv")

In [67]:
pd.set_option('display.max_columns', None)

In [68]:
country_list = ['Andorra','United Arab Emirates','Afghanistan','Antigua and Barbuda','Anguilla','Albania','Armenia','Netherlands Antilles','Angola','Antarctica','Argentina','American Samoa','Austria','Australia','Aruba','Azerbaijan','Bosnia and Herzegovina','Barbados','Bangladesh','Belgium','Burkina Faso','Bulgaria','Bahrain','Burundi','Benin','Bermuda','Brunei','Bolivia','Brazil','Bahamas','Bhutan','Bouvet Island','Botswana','Belarus','Belize','Canada','Cocos [Keeling] Islands','Congo [DRC]','Central African Republic','Congo [Republic]','Switzerland','Cook Islands','Chile','Cameroon','China','Colombia','Costa Rica','Cuba','Cape Verde','Christmas Island','Cyprus','Czech Republic','Germany','Djibouti','Denmark','Dominica','Dominican Republic','Algeria','Ecuado'","'Estonia','Egypt','Western Sahara','Eritrea','Spain','Ethiopia','Finland','Fiji','Falkland Islands [Islas Malvinas]','Micronesia','Faroe Islands','France','Gabon','United Kingdom','Grenada','Georgia','French Guiana','Guernsey','Ghana','Gibralta'","'Greenland','Gambia','Guinea','Guadeloupe','Equatorial Guinea','Greece','South Georgia and the South Sandwich Islands','Guatemala','Guam','Guinea-Bissau','Guyana','Gaza Strip','Hong Kong','Heard Island and McDonald Islands','Honduras','Croatia','Haiti','Hungary','Indonesia','Ireland','Israel','Isle of Man','India','British Indian Ocean Territory','Iraq','Iran','Iceland','Italy','Jersey','Jamaica','Jordan','Japan','Kenya','Kyrgyzstan','Cambodia','Kiribati','Comoros','Saint Kitts and Nevis','North Korea','South Korea','Kuwait','Cayman Islands','Kazakhstan','Laos','Lebanon','Saint Lucia','Liechtenstein','Sri Lanka','Liberia','Lesotho','Lithuania','Luxembourg','Latvia','Libya','Morocco','Monaco','Moldova','Montenegro','Madagasca'","'Marshall Islands','Macedonia [FYROM]','Mali','Myanmar [Burma]','Mongolia','Macau','Northern Mariana Islands','Martinique','Mauritania','Montserrat','Malta','Mauritius','Maldives','Malawi','Mexico','Malaysia','Mozambique','Namibia','New Caledonia','Nige'","'Norfolk Island','Nigeria','Nicaragua','Netherlands','Norway','Nepal','Nauru','Niue','New Zealand','Oman','Panama','Peru','French Polynesia','Papua New Guinea','Philippines','Pakistan','Poland','Saint Pierre and Miquelon','Pitcairn Islands','Puerto Rico','Palestinian Territories','Portugal','Palau','Paraguay','Qata'","'Réunion','Romania','Serbia','Russia','Rwanda','Saudi Arabia','Solomon Islands','Seychelles','Sudan','Sweden','Singapore','Saint Helena','Slovenia','Svalbard and Jan Mayen','Slovakia','Sierra Leone','San Marino','Senegal','Somalia','Suriname','São Tomé and Príncipe','El Salvado'","'Syria','Swaziland','Turks and Caicos Islands','Chad','French Southern Territories','Togo','Thailand','Tajikistan','Tokelau','Timor-Leste','Turkmenistan','Tunisia','Tonga','Turkey','Trinidad and Tobago','Tuvalu','Taiwan','Tanzania','Ukraine','Uganda','U.S. Minor Outlying Islands','United States','Uruguay','Uzbekistan','Vatican City','Saint Vincent and the Grenadines','Venezuela','British Virgin Islands','U.S. Virgin Islands','Vietnam','Vanuatu','Wallis and Futuna','Samoa','Kosovo','Yemen','Mayotte','South Africa','Zambia','Zimbabwe']

In [69]:
disaster_types = ['Drought', 'Earthquake', 'Epidemic', 'Extreme temperature', 'Flood', 'Storm', 'Volcanic activity', 'Wildfire']

In [70]:
df = df[df['Country'].isin(country_list)]

In [71]:
df = df[df['Disaster Type'].isin(disaster_types)]

In [72]:
df = df.drop('Seq', axis=1)
df = df.drop('Glide', axis=1)
df = df.drop('Disaster Group', axis=1)
df = df.drop('Disaster Subsubtype', axis=1)
df = df.drop('Event Name', axis=1)
df = df.drop('OFDA Response', axis=1)
df = df.drop('Appeal', axis=1)
df = df.drop('Associated Dis', axis=1)
df = df.drop('Associated Dis2', axis=1)
df = df.drop('Declaration', axis=1)
df = df.drop('Aid Contribution', axis=1)
df = df.drop('Local Time', axis=1)
df = df.drop('Adm Level', axis=1)
df = df.drop('Admin1 Code', axis=1)
df = df.drop('Admin2 Code', axis=1)
df = df.drop('Geo Locations', axis=1)

In [73]:
df["CPI"].fillna(100, inplace = True)

In [74]:
df["Total Damages Adjusted ('000 US$)"] = (df["Total Damages ('000 US$)"].astype(float) / (df["CPI"].astype(float)/100)).round(2)

In [75]:
# Linearly interpolate numeric columns
# Linearly interpolate numeric columns
numeric = df[['Start Day', 'Start Month', 'End Day', 'End Month', 'CPI','Total Affected', 'No Homeless', 'No Affected', 'No Injured', 'Total Deaths']]
numeric_columns = numeric.columns

df[numeric_columns] = df[numeric_columns].interpolate(method='linear',limit_direction='forward')

# Calculate the median and interquartile range of the date columns
start_month_median = df['Start Month'].median()
start_month_iqr = df['Start Month'].quantile(0.75) - df['Start Month'].quantile(0.25)

start_day_median = df['Start Day'].median()
start_day_iqr = df['Start Day'].quantile(0.75) - df['Start Day'].quantile(0.25)

end_month_median = df['End Month'].median()
end_month_iqr = df['End Month'].quantile(0.75) - df['End Month'].quantile(0.25)

end_day_median = df['End Day'].median()
end_day_iqr = df['End Day'].quantile(0.75) - df['End Day'].quantile(0.25)

# Calculate the median and interquartile range of the numeric columns
cpi_median = df['CPI'].median()
cpi_iqr = df['CPI'].quantile(0.75) - df['CPI'].quantile(0.25)

total_affected_median = df['Total Affected'].median()
total_affected_iqr = df['Total Affected'].quantile(0.75) - df['Total Affected'].quantile(0.25)

no_homeless_median = df['No Homeless'].median()
no_homeless_iqr = df['No Homeless'].quantile(0.75) - df['No Homeless'].quantile(0.25)

no_affected_median = df['No Affected'].median()
no_affected_iqr = df['No Affected'].quantile(0.75) - df['No Affected'].quantile(0.25)

no_injured_median = df['No Injured'].median()
no_injured_iqr = df['No Injured'].quantile(0.75) - df['No Injured'].quantile(0.25)

total_deaths_median = df['Total Deaths'].median()
total_deaths_iqr = df['Total Deaths'].quantile(0.75) - df['Total Deaths'].quantile(0.25)

# Replace any outliers with the median and interquartile range
df['Start Month'] = df['Start Month'].apply(lambda x: start_month_median if x > start_month_median + start_month_iqr * 1.5 or x < start_month_median - start_month_iqr * 1.5 else x)
df['Start Day'] = df['Start Day'].apply(lambda x: start_day_median if x > start_day_median + start_day_iqr * 1.5 or x < start_day_median - start_day_iqr * 1.5 else x)
df['End Month'] = df['End Month'].apply(lambda x: end_month_median if x > end_month_median + end_month_iqr * 1.5 or x < end_month_median - end_month_iqr * 1.5 else x)
df['End Day'] = df['End Day'].apply(lambda x: end_day_median if x > end_day_median + end_day_iqr * 1.5 or x < end_day_median - end_day_iqr * 1.5 else x)

df['CPI'] = df['CPI'].apply(lambda x: cpi_median if x > cpi_median + cpi_iqr * 1.5 or x < cpi_median - cpi_iqr * 1.5 else x)
df['Total Affected'] = df['Total Affected'].apply(lambda x: total_affected_median if x > total_affected_median + total_affected_iqr * 1.5 or x < total_affected_median - total_affected_iqr * 1.5 else x)
df['No Homeless'] = df['No Homeless'].apply(lambda x: no_homeless_median if x > no_homeless_median + no_homeless_iqr * 1.5 or x < no_homeless_median - no_homeless_iqr * 1.5 else x)
df['No Affected'] = df['No Affected'].apply(lambda x: no_affected_median if x > no_affected_median + no_affected_iqr * 1.5 or x < no_affected_median - no_affected_iqr * 1.5 else x)
df['No Injured'] = df['No Injured'].apply(lambda x: no_injured_median if x > no_injured_median + no_injured_iqr * 1.5 or x < no_injured_median - no_injured_iqr * 1.5 else x)
df['Total Deaths'] = df['Total Deaths'].apply(lambda x: total_deaths_median if x > total_deaths_median + total_deaths_iqr * 1.5 or x < total_deaths_median - total_deaths_iqr * 1.5 else x)

# Replace infinite values with the median and interquartile range
df['Start Month'] = df['Start Month'].apply(lambda x: start_month_median if np.isinf(x) else x)
df['Start Day'] = df['Start Day'].apply(lambda x: start_day_median if np.isinf(x) else x)
df['End Month'] = df['End Month'].apply(lambda x: end_month_median if np.isinf(x) else x)
df['End Day'] = df['End Day'].apply(lambda x: end_day_median if np.isinf(x) else x)

df['CPI'] = df['CPI'].apply(lambda x: cpi_median if np.isinf(x) else x)
df['Total Affected'] = df['Total Affected'].apply(lambda x: total_affected_median if np.isinf(x) else x)
df['No Homeless'] = df['No Homeless'].apply(lambda x: no_homeless_median if np.isinf(x) else x)
df['No Affected'] = df['No Affected'].apply(lambda x: no_affected_median if np.isinf(x) else x)
df['No Injured'] = df['No Injured'].apply(lambda x: no_injured_median if np.isinf(x) else x)
df['Total Deaths'] = df['Total Deaths'].apply(lambda x: total_deaths_median if np.isinf(x) else x)

# Replace non-finite values with the median and interquartile range
df['Start Month'] = df['Start Month'].apply(lambda x: start_month_median if not np.isfinite(x) else x)
df['Start Day'] = df['Start Day'].apply(lambda x: start_day_median if not np.isfinite(x) else x)
df['End Month'] = df['End Month'].apply(lambda x: end_month_median if not np.isfinite(x) else x)
df['End Day'] = df['End Day'].apply(lambda x: end_day_median if not np.isfinite(x) else x)

df['CPI'] = df['CPI'].apply(lambda x: cpi_median if not np.isfinite(x) else x)
df['Total Affected'] = df['Total Affected'].apply(lambda x: total_affected_median if not np.isfinite(x) else x)
df['No Homeless'] = df['No Homeless'].apply(lambda x: no_homeless_median if not np.isfinite(x) else x)
df['No Affected'] = df['No Affected'].apply(lambda x: no_affected_median if not np.isfinite(x) else x)
df['No Injured'] = df['No Injured'].apply(lambda x: no_injured_median if not np.isfinite(x) else x)
df['Total Deaths'] = df['Total Deaths'].apply(lambda x: total_deaths_median if not np.isfinite(x) else x)

# Throw away fractorial parts with a cast to int
df[
    ['Start Year','Start Month','Start Day',
     'End Year','End Month','End Day',
     'Total Affected',
     'No Homeless','No Affected','No Injured',
     'Total Deaths'
    ]
] = df[
    ['Start Year','Start Month','Start Day',
     'End Year','End Month','End Day',
     'Total Affected',
     'No Homeless','No Affected','No Injured',
     'Total Deaths'
    ]
].astype(np.int64)

# Check if the day is out of range for the given month, and if it is, increment the month by 1 and set the day to 1
def check_start_date_validity(row):
    # Get the year, month, and day
    year = row['Start Year']
    month = row['Start Month']
    day = row['Start Day']
    # Check if the month is February
    if month == 2:
        # Check if the day is greater than 28
        if day > 28:
            # Set the day to 1
            row['Start Day'] = 1
            # Increment the month by 1
            row['Start Month'] += 1
    else:
        # Get the days in the month
        days_in_month = calendar.monthrange(year, month)[1]
        # Check if the day is greater than the days in the month
        if day > days_in_month:
            # Set the day to 1
            row['Start Day'] = 1
            # Increment the month by 1
            row['Start Month'] += 1
            # Check if the month is greater than 12
            if row['Start Month'] > 12:
                # Set the month to 1
                row['Start Month'] = 1
                # Increment the year by 1
                row['Start Year'] += 1
    # Return the row
    return row

def check_end_date_validity(row):
    # Get the year, month, and day
    year = row['End Year']
    month = row['End Month']
    day = row['End Day']
    # Check if the month is February
    if month == 2:
        # Check if the day is greater than 28
        if day > 28:
            # Set the day to 1
            row['End Day'] = 1
            # Increment the month by 1
            row['End Month'] += 1
    else:
        # Get the days in the month
        days_in_month = calendar.monthrange(year, month)[1]
        # Check if the day is greater than the days in the month
        if day > days_in_month:
            # Set the day to 1
            row['End Day'] = 1
            # Increment the month by 1
            row['End Month'] += 1
            # Check if the month is greater than 12
            if row['End Month'] > 12:
                # Set the month to 1
                row['End Month'] = 1
                # Increment the year by 1
                row['End Year'] += 1
    # Return the row
    return row

# Apply the function to the dataframe
df[['Start Year','Start Month','Start Day']] = df[['Start Year','Start Month','Start Day']].apply(check_start_date_validity, axis=1)
df[['End Year','End Month','End Day']] = df[['End Year','End Month','End Day']].apply(check_end_date_validity, axis=1)

In [76]:
display(df.head(30000))

,Year,Disaster Subgroup,Disaster Type,Disaster Subtype,Country,ISO,Region,Continent,Location,Origin,Dis Mag Value,Dis Mag Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No Injured,No Affected,No Homeless,Total Affected,Insured Damages ('000 US$),Total Damages ('000 US$),CPI,Total Damages Adjusted ('000 US$)
1,1900,Climatological,Drought,Drought,India,IND,Southern Asia,Asia,Bengal,NaN,NaN,Km2,NaN,NaN,NaN,1900,7,15,1900,7,16,18,88,18000,6000,10000,NaN,NaN,68.415379,NaN
2,1902,Geophysical,Earthquake,Ground movement,Guatemala,GTM,Central America,Americas,"Quezaltenango, San Marcos",NaN,8.0,Richter,14,-91,NaN,1902,4,18,1902,4,18,18,88,18000,6000,10000,NaN,25000.0,68.415379,746154.36
3,1902,Geophysical,Volcanic activity,Ash fall,Guatemala,GTM,Central America,Americas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902,4,8,1902,4,8,18,88,18000,6000,10000,NaN,NaN,68.415379,NaN
4,1902,Geophysical,Volcanic activity,Ash fall,Guatemala,GTM,Central America,Americas,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1902,10,24,1902,10,24,18,88,18000,6000,10000,NaN,NaN,68.415379,NaN
7,1904,Meteorological,Storm,Tropical cyclone,Bangladesh,BGD,Southern Asia,Asia,Chittagong,NaN,NaN,Kph,NaN,NaN,NaN,1904,11,14,1904,11,14,18,88,18000,6000,10000,NaN,NaN,68.415379,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16115,2021,Meteorological,Storm,Tropical cyclone,Saint Vincent and the Grenadines,VCT,Caribbean,Americas,Northern half of St. Vincent,NaN,NaN,Kph,NaN,NaN,NaN,2021,7,2,2021,7,3,9,3,129,150,129,NaN,NaN,100.000000,NaN
16120,2021,Hydrological,Flood,Flash flood,Yemen,YEM,Western Asia,Asia,"Sanaa, Ibb, Shabwa, Hodeida, Aden, Abyan, Al D...",Heavy rains,NaN,Km2,NaN,NaN,NaN,2021,5,1,2021,5,17,13,3,22380,150,22380,NaN,NaN,100.000000,NaN
16121,2021,Hydrological,Flood,NaN,Yemen,YEM,Western Asia,Asia,"Dhamar, Amran, Al Mahwit, Marib, Ibb, Sana’a C...",Heavy rains,NaN,Km2,NaN,NaN,NaN,2021,7,16,2021,8,7,11,3,67980,150,67980,NaN,NaN,100.000000,NaN
16122,2021,Hydrological,Flood,NaN,South Africa,ZAF,Southern Africa,Africa,"Mpumalanga Province, Free State Province and t...",Heavy rains,NaN,Km2,NaN,NaN,NaN,2021,2,1,2021,2,15,31,3,400,150,400,NaN,75000.0,100.000000,75000.00
16124,2021,Hydrological,Flood,NaN,Serbia,SRB,Southern Europe,Europe,"Zitoradja (Toplicki), Doljevac (Nisavski) , Di...",Heavy rains,NaN,Km2,NaN,NaN,NaN,2021,1,11,2021,1,12,31,3,22,150,22,NaN,NaN,100.000000,NaN

In [77]:
df2.to_csv("disasters_clean.csv", index = True)